name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Android Build Image
        run: |
          docker build -t android-builder .

      # Run Gradle build inside container
      - name: Build APK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            android-builder ./gradlew assembleRelease

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/release/*.apk
